<template><div><h2 id="_1-前言" tabindex="-1"><a class="header-anchor" href="#_1-前言"><span>1.前言</span></a></h2>
<p>如你所见，博客小站现在已经迁移到了<mark>Vuepress</mark>框架。</p>
<p>用了一段时间的<code v-pre>Hexo</code>，最终还是离开了他。原因是在我自己开发过一段时间的<code v-pre>Hexo</code>主题后，我发现了<code v-pre>Hexo</code>目前存在的许多问题：</p>
<ul>
<li><code v-pre>Hexo</code>是一个台湾大学生开发的，在框架上主要使用模版语言主题开发效率低。</li>
<li>主题虽多，功能有限，扩展性一般。</li>
<li>性能平庸。</li>
<li>文件管理实在鸡肋。</li>
</ul>
<p>在官网阅读完<mark>Vuepress-Plume</mark>主题的文档后，我果断选择将博客迁移到了Vueperess框架。</p>
<p><code v-pre>Plume</code>的文件管理方式实在吸引我，他其他的专业性功能也强到可怕。<mark>Plume</mark>自动解析并识别文件结构，而于此对应的<code v-pre>Hexo</code>居然只可以将所有的博客文件全部摊在一个<code v-pre>_posts</code>文件夹中，这是何等的悲哀。</p>
<p><code v-pre>Vue</code>，一个<mark>T0级别</mark>的前端框架。基于Vue的Vuepress，提供的功能也非常多，其中杀手级功能数不胜数，我一个羸弱blogger在Plume面前完全没有任何抵抗力。可以说，<code v-pre>Plume</code>这种既面向文档又面向博客的框架，简直就是我这种简约风狂热者的梦中主题。</p>
<p>说个有意思的，我自己开发的主题居然和<code v-pre>Plume</code>在设计风格上相似度极高。</p>
<blockquote>
<p>这我还开发个锤锤，人家都把我梦想中的主题开发好喂我嘴里了...</p>
</blockquote>
<h2 id="_2-问题" tabindex="-1"><a class="header-anchor" href="#_2-问题"><span>2.问题</span></a></h2>
<p>在部署<code v-pre>Vuepress</code>的过程中，由于其设计的不同出现了些许问题。</p>
<p>之前部署Hexo我使用的是私有仓库存放源代码，Gitpage仓库存放静态打包📦资源的方式。本地推送代码到源码仓库后Gitactions将静态资源同步到Gitpage仓库。</p>
<p>而<code v-pre>Vuepress</code>中默认的方式是在Gitpage仓库中建立一个分支存放源码并将打包资源也放在本仓库中。</p>
<p>我一开始没意识到这个问题，仍然采用双仓库部署。结果复用文档的部署工作流代码时才发现部署到了源代码的仓库中。</p>
<p>第二个是权限的问题。</p>
<p>在发现了问题一后，我在Gitpage中用main分支来保管源码。在使用官方<code v-pre>workflows/docs.yml</code>时发现推送会报一个权限的错误：</p>
<p><img src="https://ccccooh.oss-cn-hangzhou.aliyuncs.com/img/截屏.png" alt="截屏"></p>
<p>查阅相关资料才发现，是仓库中权限没给够，去仓库的<code v-pre>Settings/Actions</code>中将权限拉高即可。</p>
<p>在这期间，我发现来到新疆之后网络🛜环境变得非常迷，有时候push到github非常慢，甚至时常失败告终。</p>
<p>在推送的过程中可以说是煎熬。</p>
<p><img src="https://ccccooh.oss-cn-hangzhou.aliyuncs.com/img/截屏.png" alt="截屏"></p>
<p>同时，在多设备写博客的过程中也发现了<code v-pre>Picgo</code>的一些问题，也算是小Bug吧。Vscode中的Picgo插件需要配置<code v-pre>data.json</code>的文件目录，但是频繁更换设备就会导致这个目录更换，更换设备后必须卸载再重新配置目录，否则容易出错。</p>
<p>回归正题，选择了单仓库多分枝的部署方式后，还存在一个问题。</p>
<p>在配置了域名后，必须在官方提供的workflow文件中加上一行配置CNAME域名的代码，否则就会出现page404，原因也是没有重新解析域名导致的。</p>
<p>因为这个时候无法访问域名，但是却可以正常访问username.github.io。</p>
<p>并且，如果手动在Gitpage配置CNAME，再次推送文件仍然会被覆盖，所以需要加上这行代码：</p>
<div class="language-yml line-numbers-mode has-collapsed collapsed" data-ext="yml" data-title="yml" style="--vp-collapsed-lines:15;"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span>name:</span><span class="space"> </span><span>docs</span></span>
<span class="line"><span></span></span>
<span class="line"><span>on:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>每当</span><span class="space"> </span><span>push</span><span class="space"> </span><span>到</span><span class="space"> </span><span>main</span><span class="space"> </span><span>分支时触发部署</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span>push:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>branches:</span><span class="space"> </span><span>[main]</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>手动触发部署</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span>workflow_dispatch:</span></span>
<span class="line"><span></span></span>
<span class="line"><span>jobs:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span>docs:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>runs-on:</span><span class="space"> </span><span>ubuntu-latest</span></span>
<span class="line"><span></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>steps:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>-</span><span class="space"> </span><span>uses:</span><span class="space"> </span><span>actions/checkout@v4</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>with:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>“最近更新时间”</span><span class="space"> </span><span>等</span><span class="space"> </span><span>git</span><span class="space"> </span><span>日志相关信息，需要拉取全部提交记录</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>fetch-depth:</span><span class="space"> </span><span>0</span></span>
<span class="line"><span></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>-</span><span class="space"> </span><span>name:</span><span class="space"> </span><span>Setup</span><span class="space"> </span><span>pnpm</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>uses:</span><span class="space"> </span><span>pnpm/action-setup@v4</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>with:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>选择要使用的</span><span class="space"> </span><span>pnpm</span><span class="space"> </span><span>版本</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>version:</span><span class="space"> </span><span>10.4.1</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>使用</span><span class="space"> </span><span>pnpm</span><span class="space"> </span><span>安装依赖</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>run_install:</span><span class="space"> </span><span>true</span></span>
<span class="line"><span></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>-</span><span class="space"> </span><span>name:</span><span class="space"> </span><span>Setup</span><span class="space"> </span><span>Node.js</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>uses:</span><span class="space"> </span><span>actions/setup-node@v4</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>with:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>选择要使用的</span><span class="space"> </span><span>node</span><span class="space"> </span><span>版本</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>node-version:</span><span class="space"> </span><span>20</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>缓存</span><span class="space"> </span><span>pnpm</span><span class="space"> </span><span>依赖</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>cache:</span><span class="space"> </span><span>pnpm</span></span>
<span class="line"><span></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>运行构建脚本</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>-</span><span class="space"> </span><span>name:</span><span class="space"> </span><span>Build</span><span class="space"> </span><span>VuePress</span><span class="space"> </span><span>site</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>run:</span><span class="space"> </span><span>pnpm</span><span class="space"> </span><span>docs:build</span></span>
<span class="line"><span></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>查看</span><span class="space"> </span><span>workflow</span><span class="space"> </span><span>的文档来获取更多信息</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>@see</span><span class="space"> </span><span>https://github.com/crazy-max/ghaction-github-pages</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>-</span><span class="space"> </span><span>name:</span><span class="space"> </span><span>Deploy</span><span class="space"> </span><span>to</span><span class="space"> </span><span>GitHub</span><span class="space"> </span><span>Pages</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>uses:</span><span class="space"> </span><span>crazy-max/ghaction-github-pages@v4</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>with:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>部署到</span><span class="space"> </span><span>gh-pages</span><span class="space"> </span><span>分支</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>target_branch:</span><span class="space"> </span><span>gh-pages</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>部署目录为</span><span class="space"> </span><span>VuePress</span><span class="space"> </span><span>的默认输出目录</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>build_dir:</span><span class="space"> </span><span>docs/.vuepress/dist</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>fqdn:</span><span class="space"> </span><span>shenying.online</span><span class="space"> </span><span>#</span><span class="space"> </span><span>[!code</span><span class="space"> </span><span>focus]</span><span class="space"> </span><span>[!code</span><span class="space"> </span><span>highlight]</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>env:</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>#</span><span class="space"> </span><span>@see</span><span class="space"> </span><span>https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret</span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span>GITHUB_TOKEN:</span><span class="space"> </span><span>${{ secrets.GITHUB_TOKEN }}</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="collapsed-lines"></div></div><blockquote>
<p>顺便提一嘴，这是<code v-pre>Plume</code>提供的代码聚焦聚焦功能，是不是非常强大！
除此之外还有各种颜色的代码行高亮功能，代码块错误警告提示、词高亮、空白符号、代码块折叠等等，并且这些都是可供选择而非强制的！！</p>
</blockquote>
<p>完成之后，基本就可以轻松撰写博客了，只需要推送到主要分枝GithubActions就会自动同步到分枝<code v-pre>gp-pages</code>，我们将Gitpage的渲染branch切换到这个分枝即可。</p>
<p>对了，我也发现Vscode的推送功能在博客LiveServer预览的时候时常会很慢。</p>
</div></template>


